/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "outline": "#859398",
          "primary-container": "#00d4ff",
          "primary": "#a8e8ff",
          "error-container": "#93000a",
          "surface-container": "#1a2123",
          "surface-container-high": "#242b2e",
          "on-secondary-fixed": "#1a0063",
          "surface-container-highest": "#2f3639",
          "tertiary-fixed-dim": "#ffb1c5",
          "inverse-primary": "#00677e",
          "primary-fixed-dim": "#3cd7ff",
          "on-primary-fixed": "#001f27",
          "surface-variant": "#2f3639",
          "on-background": "#dde3e7",
          "surface-bright": "#333a3d",
          "on-error": "#690005",
          "tertiary-container": "#ffabc1",
          "surface-dim": "#0e1417",
          "secondary": "#c9bfff",
          "surface": "#0e1417",
          "on-secondary-container": "#baaeff",
          "on-primary-container": "#00586b",
          "on-secondary": "#2e009c",
          "surface-container-lowest": "#080f12",
          "tertiary": "#ffd4dd",
          "on-tertiary-container": "#99194f",
          "on-primary-fixed-variant": "#004e5f",
          "tertiary-fixed": "#ffd9e1",
          "on-tertiary": "#650030",
          "background": "#0e1417",
          "inverse-surface": "#dde3e7",
          "on-surface-variant": "#bbc9cf",
          "inverse-on-surface": "#2b3134",
          "surface-container-low": "#161d1f",
          "on-surface": "#dde3e7",
          "on-primary": "#003642",
          "secondary-fixed-dim": "#c9bfff",
          "primary-fixed": "#b4ebff",
          "on-tertiary-fixed-variant": "#8c0a46",
          "secondary-fixed": "#e5deff",
          "on-secondary-fixed-variant": "#441cc8",
          "surface-tint": "#3cd7ff",
          "on-tertiary-fixed": "#3f001b",
          "secondary-container": "#4720ca",
          "error": "#ffb4ab",
          "on-error-container": "#ffdad6",
          "outline-variant": "#3c494e"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter": "1.5rem",
          "sm": "0.5rem",
          "margin": "2rem",
          "xl": "2rem",
          "grid_columns": "12",
          "md": "1rem",
          "lg": "1.5rem",
          "2xl": "3rem",
          "3xl": "4rem",
          "xs": "0.25rem"
      },
      "fontFamily": {
          "h4": ["Inter"],
          "body-lg": ["Inter"],
          "code": ["JetBrains Mono"],
          "tech-label": ["JetBrains Mono"],
          "h1": ["Inter"],
          "h2": ["Inter"],
          "body-md": ["Inter"],
          "h3": ["Inter"],
          "orbitron": ["Orbitron", "sans-serif"]
      },
      "fontSize": {
          "h4": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
          "code": ["13px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
          "tech-label": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
          "h1": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "800" }],
          "h2": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
          "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
          "h3": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
